services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./Building-services-master/backend
    image: sudhan1112/building-backend:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/blog
      - PORT=3000
    depends_on:
      - mongo
    ports:
      - "5000:3000"

  frontend:
    build:
      context: ./Building-services-master/frontend
    image: sudhan1112/building-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:



